import { FlashcardsIcon } from "@/app/_components/FlashcardsIcon";
import NavigationLink from "@/app/_components/NavigationLink";
import UserNavigationLink from "@/app/_components/UserNavigationLink";
import "@/app/globals.css";
import { Menu } from "@base-ui/react/menu";
import "material-symbols";
import "material-symbols/outlined.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Learn Burmese",
  description: "Generated by create next app",
};

const navigationLinks = [
  { name: "Flashcards", href: "/" },
  { name: "Dashboard", href: "/dashboard" },
];

const userNavigationLinks = [
  { name: "Profile", href: "/profile" },
  { name: "Sign out", href: "/sign-out" },
];

export default function Layout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`flex h-screen flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex h-16 justify-between border-b border-gray-700 bg-gray-900 px-8">
          <div className="flex items-center">
            <FlashcardsIcon className="w-8 text-indigo-500" />

            <div className="ms-2 flex flex-col text-xs font-bold text-indigo-500 select-none">
              <span>Learn</span>
              <span>Burmese</span>
            </div>

            <nav className="ms-12 flex h-full space-x-6">
              {navigationLinks.map((link) => (
                <NavigationLink
                  key={link.name}
                  name={link.name}
                  href={link.href}
                />
              ))}
            </nav>
          </div>

          <Menu.Root>
            <Menu.Trigger
              className="material-symbols-outlined cursor-pointer self-center text-gray-400 transition-all ease-in-out select-none hover:text-white"
              style={{ fontSize: "32px" }}
            >
              account_circle
            </Menu.Trigger>

            <Menu.Portal>
              <Menu.Positioner sideOffset={8}>
                <Menu.Popup className="origin-(--transform-origin) transition-all ease-in-out data-ending-style:scale-90 data-ending-style:opacity-0 data-starting-style:scale-90 data-starting-style:opacity-0">
                  {userNavigationLinks.map((link, index) => (
                    <UserNavigationLink
                      key={link.name}
                      name={link.name}
                      href={link.href}
                      index={index}
                      numberOfNavigationLinks={userNavigationLinks.length}
                    />
                  ))}
                </Menu.Popup>
              </Menu.Positioner>
            </Menu.Portal>
          </Menu.Root>
        </header>

        <div className="flex flex-1">{children}</div>
      </body>
    </html>
  );
}
